/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisForm: typeof import('./src/components/AnalysisForm.vue')['default']
    AnalysisResults: typeof import('./src/components/AnalysisResults.vue')['default']
    AnalysisStatusDialog: typeof import('./src/components/AnalysisStatusDialog.vue')['default']
    MetricBarCharts: typeof import('./src/components/charts/MetricBarCharts.vue')['default']
    MetricBoxPlots: typeof import('./src/components/charts/MetricBoxPlots.vue')['default']
    MetricsCharts: typeof import('./src/components/charts/MetricsCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
