services:
    api:
        build:
            context: ./api_service
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - ./api_service/.env.development.local
        volumes:
            - ./api_service:/app
        environment:
            - ENV=development
        networks:
            - analyzer-network
        depends_on:
            - runner

    runner:
        build:
            context: ./runner_service
            dockerfile: Dockerfile
        expose:
            - "8080"
        env_file:
            - ./runner_service/.env.development.local
        volumes:
            - ./runner_service:/app
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ENV=development
        networks:
            - analyzer-network
        privileged: true

    frontend:
        build:
            context: ./frontend
            args:
                - VITE_ENV=development
        ports:
            - "3000:80"
        env_file:
            - ./frontend/.env.development.local
        depends_on:
            - api
        networks:
            - analyzer-network

networks:
    analyzer-network:
        driver: bridge
