name: Развёртывание на VPS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Подключение по SSH и развёртывание
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  port: 22
                  script: |
                      cd git/ITMO_nir_4
                      git pull
                      docker compose down
                      docker compose -f docker-compose.prod.yml up --build -d
                      echo "Deploy complete"
